services:
  tensorflow_serving:
    image: tensorflow/serving:latest-gpu
    container_name: model
    ports:
      - "8501:8501"
    volumes:
      - /models:/models
      - /models.config:/models/models.config
    command: >
      tensorflow_model_server
      --model_config_file=/models/models.config
      --allow_version_labels_for_unavailable_models=true
      --rest_api_port=8501
    restart: always
